// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "RIP.h"

namespace plugin {
namespace Bro_RIP {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("RIP",
		             ::analyzer::RIP::RIP_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::RIP";
		config.description = "Routing Internet Protocol analyzer";
		return config;
		}
} plugin;

}
}