// Generated by binpac_quickstart

#include "RIP.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::RIP;

RIP_Analyzer::RIP_Analyzer(Connection* c)

: analyzer::Analyzer("RIP", c)

	{
	interp = new binpac::RIP::RIP_Conn(this);

	}

RIP_Analyzer::~RIP_Analyzer()
	{
	delete interp;
	}

void RIP_Analyzer::Done()
	{

	Analyzer::Done();

	}

void RIP_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64 seq, const IP_Hdr* ip, int caplen)
	{
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}
